services:
  - type: web
    name: team-x-bank
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn mamar_bank.wsgi:application --bind 0.0.0.0:$PORT --log-file -"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mamar_bank.settings
    preDeployCommand: "python manage.py migrate --noinput && python manage.py collectstatic --noinput"
    autoDeploy: true
    pullRequestPreviews: false
